name: CI - Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

  train:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Entraînement du modèle
        run: python train.py

  docker-build:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker
        run: docker build -t breast-cancer-api .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Entraînement du modèle
        run: python train.py

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/tagaingne/breast-cancer-api:latest
          